extends Object
class_name SexGoal

const FuckVaginal = "FuckVaginal"
const FuckAnal = "FuckAnal"
const FuckOral = "FuckOral"
const Fuck69 = "Fuck69"
const ReceiveVaginal = "ReceiveVaginal"
const ReceiveAnal = "ReceiveAnal"
const DoOralOnSub = "DoOralOnSub"
const DoFeetplay = "DoFeetplay"
const Pawjob = "Pawjob"
const Tribadism = "Tribadism"
const StraponVaginal = "StraponVaginal"
const StraponAnal = "StraponAnal"
const ReceiveStraponVaginal = "ReceiveStraponVaginal"
const ReceiveStraponAnal = "ReceiveStraponAnal"

const TieUp = "TieUp"
const AddBodywritings = "AddBodywritings"
const AddTallymarks = "AddTallymarks"
const Choke = "Choke"
const ChokeSexVaginal = "ChokeSexVaginal"
const ChokeSexAnal = "ChokeSexAnal"
const ChokeReceiveVaginal = "ChokeReceiveVaginal"
const ChokeReceiveAnal = "ChokeReceiveAnal"
const SpankSub = "SpankSub"

const RimSub = "RimSub"
const RimmingReceive = "RimmingReceive"
const MilkWithBreastPump = "MilkWithBreastPump"
const GropeBreasts = "GropeBreasts"
const BreastFeedOnSub = "BreastFeedOnSub"
const BreastFeedSub = "BreastFeedSub"
const MilkWithPenisPump = "MilkWithPenisPump"

const Hypnotize = "Hypnotize"
const UseTFDrug = "UseTFDrug"
const Cuddle = "Cuddle"

# Subgoals, these don't need classes defined
const SubUndressSub = "SubUndressSub"
const SubUndressDom = "SubUndressDom"
const SubOptionalCondomOnSub = "SubOptionalCondomOnSub"
const SubOptionalCondomOnDom = "SubOptionalCondomOnDom"
const SubWearStraponOnSub = "SubWearStraponOnSub"
const SubWearStraponOnDom = "SubWearStraponOnDom"
const SubChoking = "SubChoking"
const SubOptionalApplyLubeOnSub = "SubOptionalApplyLubeOnSub"
const SubOptionalApplyLubeOnDom = "SubOptionalApplyLubeOnDom"
const SubMakeUnconscious = "SubMakeUnconscious"
