extends Object
class_name BuffAttribute

const RestraintRecovery = "RestraintRecovery"
const RestraintForcingSuccess = "RestraintForcingSuccess"
const BreastsMaxLactatingSize = "BreastsMaxLactatingSize"
const BreastsSize = "BreastsSize"
const BreastsMilkProduction = "BreastsMilkProduction"
const PenisCumProduction = "PenisCumProduction"
const PenisBallsVolume = "PenisBallsVolume"
const BlockArmor = "BlockArmor"
const DefocusArmor = "DefocusArmor"
const CumGenerationAfterOrgasm = "CumGenerationAfterOrgasm"
const StaminaRecoverAfterSex = "StaminaRecoverAfterSex"
const MeleeWeaponsDamage = "MeleeWeaponsDamage"
const EncounterChanceModifierStaff = "EncounterChanceModifierStaff"
const EncounterChanceModifierInmates = "EncounterChanceModifierInmates"
const FinalFertilityModifier = "FinalFertilityModifier"
const FinalVirilityModifier = "FinalVirilityModifier"
const PregnancySpeed = "PregnancySpeed"
const ForcedObedience = "ForcedObedience"
const RestEffectiveness = "RestEffectiveness"
