extends DialogueFormBank

func getForms() -> Dictionary:
	return {
		"SoftSlaveryIntro1": form("You're up? Good.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryIntro2": form("Hey. From this point on, you are now my {main.npcSlave}. Understand?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryIntro3": form("You will do as I say. Otherwise, we will have a problem.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryIntroEND": form("I will be checking on you ever so often. Don't forget who you belong to.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryChangeName": form("How should I call my {npc.npcSlave} then?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryChangeNameEND": form("Alright. You will now be my {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryAttackReaction": form("You're gonna regret it.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryAttackLost": form("Ugh.. so? You're still my {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryAttackWon": form("And now.. I'm gonna punish you.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryAskedFreedom": form("I guess I can. No point in me bugging you any further, you already know that you are my {npc.npcSlave}. Do you really want that though?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryAskedFreedomPay": form("I'm willing to let you go. But only if you pay me <CREDITS> first.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryAskedFreedomEND": form("Alright, well. Go away then.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryTalkStart": form("What do you want, {npc.npcSlave}?", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryProtectedByFriendStart": form("Hey, what are you doing with {pc.name}?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryProtectedByFriendResponse": form("It's none of your business. Step aside.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryProtectedByFriendAllGoodResp": form("Alright. Whatever then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryProtectedByFriendLost": form("Now go away while you still can.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryProtectedByFriendWonThank": form("You're welcome.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryChokeOutStart": form("I'm so fucking mad. I need a toy to abuse and you seem good enough, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryChokeOutEndured": form("I feel so much better. Thanks, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryChokeOutPCWon": form("Ugh. Why are you such a bitch?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryChokeOutPCLost": form("Such a weak {npc.npcSlave}. Can't even take some fucking abuse.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryChokeOutPCLostSex": form("Get over here.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryFuckStart": form("I wanna fuck my {npc.npcSlave}. Come here.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckResultGood": form("Not bad for a {npc.npcSlave}. I will be back when I'm horny again.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckResultOkay": form("That was okay. Can't you moan a little louder, {npc.npcSlave}? I will be back when I'm horny again.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckResultBad": form("That was awful. Are you trying to make me mad, {npc.npcSlave}? Whatever, I will be back soon.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryFuckNemesisApproach": form("Well-well-well, what do we have here?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckNemesisAsk": form("What's your problem?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckNemesisAnswer": form("Your slave crossed me. Wanna punish {pc.him} together?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckNemesisYes": form("Sure. Let's do it.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckNemesisNo": form("No. {pc.He} {pc.isAre} mine.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryFuckJealousStart": form("Hey! That is my slave! The fuck are you doing with {pc.him}?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousFight": form("Huh? Go fuck yourself. This slave is my {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerWon": form("This is my {npc.npcSlave}. Do you understand that now?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerWonFuck": form("Shouldn't have come here. Now you're gonna be my fucktoy too.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerLostOffer": form("Hey! Hear me out. How about we.. share this {npc.npcSlave} together?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerLostOffer2": form("It's the slave's fault that {pc.he} didn't tell us about each other, right? So why not punish {pc.him} instead?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerLostOfferAgree": form("You might be right.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerLostOfferAgree2": form("Let's have some fun.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckJealousOwnerLostOfferNope": form("Huh. You're funny. I think I will just fuck both of you.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaverySlutwallStart": form("Today I feel like fucking you in the slutwall. Stay still while I leash you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaverySlutwallLocked": form("Let's have some fun.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryStocksStart": form("I decided what I wanna do. I'm gonna fuck you in the stocks while everyone is watching. Stay still.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryStocksLocked": form("Let's have some fun.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryGiveCreditsStart": form("I'm short on credits, I need exactly <CREDITS> right now. Be a good {npc.npcSlave} and give them to me.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGiveCreditsTake": form("Thanks. Good {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGiveCreditsShort": form("Bullshit. Guess I will just have to punish you.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryMarkingStart": form("I feel like marking my {npc.npcSlave}. So stand still while I do this.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingEnough": form("That should be enough. Looks great.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingAnother": form("Another one?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNoStart": form("Whatever, I guess I'm not marking you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNo": form("Alright. I guess this is enough for now.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNoFail": form("Don't anger me. My {npc.npcSlave} needs to be marked.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegYes": form("You are being so cute, begging me. How can I say no?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegYes2": form("That's enough then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegNo": form("If you're gonna beg, do it on your knees.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegNo2": form("Kneel, now.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegCredits": form("Good. Now give me 5 credits or I will leave some ink on you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegCreditsGive": form("Thanks. These are more useful to me anyway.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegCreditsGive2": form("I guess thats it then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegNoMarked": form("That's what you get. Enjoy the marks.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegFoot": form("Good. Now kiss my {npc.foot}, worship me if you don't want to get inked.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegFootKiss": form("What a slut. Ready to do anything to not get marked.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegFootKiss2": form("That's it then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegHumiliation": form("Good. Now admit that you are my {npc.npcSlave}. Nothing but my property.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegHumiliation2": form("What? A little louder.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegHumiliation3": form("That's much better. Glad you agree with me.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingBegHumiliation4": form("That's it then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNotDone": form("Actually.. you know what.. I'm not done with you just yet.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNotDoneStocks": form("This is just so you don't run away now.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNotDoneStocks2": form("Perfect. This is art.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNotDoneUrinal": form("Gonna mark you real good.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryMarkingNotDoneUrinal2": form("Mmhh.. Good {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryParadeAroundStart": form("I wanna parade you around the prison. And show off my {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundFirst": form("Like it so far? We're just getting started.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundMore": form("Good. Let's walk more.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundLast": form("One more time. I want everyone to see you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundFree": form("Perfect. You're free for now, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundEatGagged": form("Too bad you can't eat, {npc.npcSlave}. I will though.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundEat": form("Lets take a break. Enjoy your meal, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundPlatform": form("Gonna lock you into one of these if you don't behave.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeAroundShower": form("Can't let you stay messy all the time.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryThreesomeStart": form("I brought a friend today. You're gonna service both of us.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishCredits": form("I will take some of that.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishCredits2": form("If I can't have your obedience, I will at least have some of your credits. Obey or I will have to do something much worse.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishRipClothes": form("That's enough for you? Yeah? Obey or I will have to do something much worse.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishRoughSex": form("Fuck it. If you don't wanna obey, I will make you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishRoughSexPCWon": form("Ugh.. I'm not done with you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishRoughSexEnded": form("Obey next time. Or I will have to do something much worse.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishSlutwall": form("Follow or I will break your legs and pull you along the floor.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishSlutwallLock": form("Enjoy being used.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishStocks": form("Follow or I will break your legs and pull you along the floor.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksLock": form("I'm sick of you. Gonna find someone else to use you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAsk": form("Is {pc.he} free to use?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAskNope": form("Nope. <CREDITS> credits and you can do whatever you want with {pc.him}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAskNoBuy": form("What if I don't wanna pay?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAskNoBuy2": form("Go away then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAskNoBuy3": form("I don't wanna do that either.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAskSure": form("Sure.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAfterSex": form("You better obey next time. I'm serious. Thanks for being such a good whore. Enjoy your stay.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAfterBadSex": form("That sucked. Give me my credits back.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksAfterBadSex2": form("That's not how it works. You used my {npc.npcSlave}, now go away.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerLost": form("Pathetic display.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerLost2": form("Much better. Enjoy yourself. Both of you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerLost3": form("Much better. And now your little slave will watch as I punish you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerWon": form("Learn your place.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerWon2": form("You as well. You are on some very thin ice, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerWon3": form("And now you're gonna learn your place.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishStocksOwnerWon4": form("And you watch. You are on some very thin ice, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishSell": form("I'm just so sick of you. I'm done. I hate you. I don't want to see you ever again.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishSell2": form("I will let someone else deal with your bullshit.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishGB": form("I'm so getting annoyed with you. Let's see how you will like a whole ass gangbang.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBGiveup": form("Whatever. You're lucky there is not enough people around.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBOffer": form("Hey. Do you wanna help me punish this {npc.npcSlave}?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBSure": form("Sure. I can do that.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBFollow": form("Follow then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBSubOffer": form("Mmm.. maybe you can punish me too?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBSubOfferYes": form("I guess we could use some extra fuckmeat.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBSubOfferNo": form("We already have an extra bitch.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBSubOfferNoAw": form("Aw.. Oh well.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBNo": form("I will pass.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBNoReact": form("Well screw you then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBStart": form("Time to teach you a lesson.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryPunishGBEnd": form("You're on very thin ice from now on, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryResist": form("Really, {npc.npcSlave}? Is that how you wanna do this?", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryFuckInStocksExtra": form("Hey! I wanna fuck them too.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckInStocksExtraYes": form("Sure, let's do it. Help me lock {pc.him} in.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckInStocksExtraNo": form("No. This is my {npc.npcSlave}, fuck off.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckInStocksExtraNo2": form("Really? I wasn't asking.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckInStocksExtraFree": form("You're free, for now.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryFuckInStocksExtraFreeLost": form("You are still my {npc.npcSlave}, understand?", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryParadeFuckOffer": form("That's a nice slave you have here. Can I fuck {pc.him}?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferYes": form("You know what? Sure. Make that slut squirm.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferYesThree": form("You know what? Sure. I will join as well.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferNo": form("No. Go away.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferNo2": form("Fine.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferGood": form("Good little slut. Let's continue.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferFight": form("I see. You just need someone to teach you a lesson.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferWon": form("You're not getting rid of me so easily.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferLostWatch": form("You're mine now. Your stupid owner can watch.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeFuckOfferLostBoth": form("You're mine now. Actually.. I will fuck both of you.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryParadeGuard": form("Hey. What is happening here?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardPunish": form("I'm punishing this inmate.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardPunish2": form("Carry on then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardProblem": form("That's none of your business.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardProblem2": form("Really?", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardWon": form("You're not getting rid of me so easily.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryParadeGuardLost": form("Go away, inmate.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryPunishSkip": form("You're lucky that I'm feeling kind today, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskSlutGive": form("I want you to do something very slutty for me, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskProstitutionGive": form("I have a task for you, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskCheck": form("It better be done the next time I check on you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryCheckTaskFail": form("I get a very strong feeling that you didn't do what I asked you to do. Gonna have to punish you then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryCheckTaskGood": form("Good job. You've done exactly as I've asked.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryCheckTaskGood2": form("You're free for now, I will find you when I need you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskFuckOwner": form("I'm feeling a bit.. subby today. Which means that you're gonna make me feel good, {npc.npcSlave}. Right now.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskFuckOwnerGood": form("That felt good.. really good. Thanks.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryTaskFuckOwnerBad": form("Really? Did you even try? I will have to punish you for this.", {main=CHAR, target=CHAR}, "main", "target"),

		"SoftSlaveryGB": form("Today I'm wanna do a gangbang on you with whoever else I can find. You might even earn some credits.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBGiveup": form("Oh well, looks like this isn't happening today. Maybe some other time.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBOffer": form("Hey. Do you wanna join to gangbang my {npc.npcSlave}? For a fair price.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBSure": form("Sure. Sounds good.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBFollow": form("Follow then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBSubOffer": form("Mmm.. maybe I can be gangbanged too? I can pay.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBSubOfferYes": form("I guess we could use some extra fuckmeat.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBSubOfferNo": form("We already have an extra slut.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBSubOfferNoAw": form("Aw.. Oh well.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBNo": form("I will pass.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBNoReact": form("Well screw you then.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBStart": form("Time to have some fun.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryGBEnd": form("Feeling satisfied, yet? There you go. This is your share, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),
		
		"SoftSlaveryLockRestraint": form("Today I feel like locking something onto you.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryLockRestraint2": form("Which one do you like the most, I'm generous enough to let you choose.", {main=CHAR, target=CHAR}, "main", "target"),
		"SoftSlaveryLockRestraint3": form("I will keep the key. Don't try to struggle it off, {npc.npcSlave}.", {main=CHAR, target=CHAR}, "main", "target"),

		"SoftSlavery": form("", {main=CHAR, target=CHAR}, "main", "target"),
	}
