extends Object
class_name StageScene

const Nothing = "Nothing"
const Solo = "SoloScene"
const Duo = "DuoScene"
const SexStart = "SexStart"
const SexCowgirl = "SexCowgirl"
const SexAllFours = "SexAllFours"
const SexOral = "SexOral"
const SexHandjob = "SexHandjob"
const SexTribadism = "SexTribadism"
const SexFeetPlay = "SexFeetPlay"
const SexFaceSitting = "SexFaceSitting"
const SexStanding = "SexStanding"
const SexMissionary = "SexMissionary"
const Stocks = "Stocks"
const StocksSex = "StocksSex"
const StocksSexOral = "StocksSexOral"
const StocksSpitroast = "StocksSpitroast"
const Cryopod = "Cryopod"
const Sybian = "Sybian"
const Urinal = "Urinal"
const HangingSexFuckmachine = "HangingSexFuckmachine"
const HangingSex = "HangingSex"
const HangingDuo = "HangingDuo"
const HangingSolo = "HangingSolo"
const HorsecockDildoSex = "HorsecockDildoSex"
const SoloEditable = "SoloEditable"
