extends Object
class_name Perk

# Starting perks
const StartInfertile = "StartInfertile"
const StartMaleInfertility = "StartMaleInfertility"
const StartNoHybrids = "StartNoHybrids"
const StartNoHeat = "StartNoHeat"
const StartMaleChastity = "StartMaleChastity"

# Combat perks
const CombatShove = "CombatShove"
const CombatRam = "CombatRam"
const CombatBetterBlock = "CombatBetterBlock"
const CombatBetterBlockV2 = "CombatBetterBlockV2"
const CombatBetterBlockV3 = "CombatBetterBlockV3"
const CombatScratching = "CombatScratching"
const CombatBetterGetUp = "CombatBetterGetUp"
const CombatDoubleDown = "CombatDoubleDown"
const CombatDrunkenMaster = "CombatDrunkenMaster"
const CombatFullStaminaBonus = "CombatFullStaminaBonus"
const CombatBetterMeleeWeapons = "CombatBetterMeleeWeapons"
const CombatBetterMeleeWeaponsV2 = "CombatBetterMeleeWeaponsV2"
const CombatBetterMeleeWeaponsV3 = "CombatBetterMeleeWeaponsV3"

# Cum Lover perks
const CumBreath = "CumBreath"
const CumBreathV1 = "CumBreathV1"
const CumBreathV2 = "CumBreathV2"
const CumSlut = "CumSlut"
const CumSwallower = "CumSwallower"
const CumSloppySeconds = "CumSloppySeconds"
const CumCumOnOpponent = "CumCumOnOpponent"
const CumKeepCondoms = "CumKeepCondoms"
const CumWhoreStreak = "CumWhoreStreak"
const CumUniqueBiology = "CumUniqueBiology"

# Sex Slave perks
const SexLustPassion = "SexLustPassion"
const SexLustPassionV2 = "SexLustPassionV2"
const SexLustPassionV3 = "SexLustPassionV3"
const SexBetterDefocus = "SexBetterDefocus"
const SexBiter = "SexBiter"
const SexBetterTease = "SexBetterTease"
const SexEdging = "SexEdging"
const SexDefocusNeverLose = "SexDefocusNeverLose"
const SexIntoxicationBonus = "SexIntoxicationBonus"

# Exhibitionism perks
const NakedNoShame = "NakedNoShame"
const NakedDodging = "NakedDodging"
const NakedDodgingV2 = "NakedDodgingV2"
const NakedDodgingV3 = "NakedDodgingV3"
const NakedMagicHips = "NakedMagicHips"
const NakedStunningLips = "NakedStunningLips"
const NakedExtraStamina = "NakedExtraStamina"
const NakedExtraStaminaV2 = "NakedExtraStaminaV2"

# BDSM perks
const BDSMGagTalk = "BDSMGagTalk"
const BDSMBlindfold = "BDSMBlindfold"
const BDSMBondageSlut = "BDSMBondageSlut"
const BDSMCollector = "BDSMCollector"
const BDSMBetterKeys = "BDSMBetterKeys"
const BDSMTallyMarks = "BDSMTallyMarks"
const BDSMBetterStruggling = "BDSMBetterStruggling"
const BDSMInstantEscape = "BDSMInstantEscape"
const BDSMRigger = "BDSMRigger"
const BDSMRiggerV2 = "BDSMRiggerV2"
const BDSMRiggerV3 = "BDSMRiggerV3"
const BDSMPerfectStreak = "BDSMPerfectStreak"

# Milking perks
const MilkSquirt = "MilkSquirt"
const MilkSelfFeed = "MilkSelfFeed"
const MilkBiggerBreasts = "MilkBiggerBreasts"
const MilkBiggerBreastsV2 = "MilkBiggerBreastsV2"
const MilkBiggerBreastsV3 = "MilkBiggerBreastsV3"
const MilkFasterProduction = "MilkFasterProduction"
const MilkFasterProductionV2 = "MilkFasterProductionV2"
const MilkFasterProductionV3 = "MilkFasterProductionV3"
const MilkNoSoreNipples = "MilkNoSoreNipples"

# Fertility perks
const FertilityBetterOvulation = "FertilityBetterOvulation"
const FertilityDesireToBreed = "FertilityDesireToBreed"
const FertilityProudMom = "FertilityProudMom"
const FertilityBetterOvulationV2 = "FertilityBetterOvulationV2"
const FertilityBroodmother = "FertilityBroodmother"
const FertilitySubmissiveAndBreedable = "FertilitySubmissiveAndBreedable"
const FertilityPainTolerance = "FertilityPainTolerance"
const FertilityBetterOvulationV3 = "FertilityBetterOvulationV3"
const FertilityMotherOfTheYear = "FertilityMotherOfTheYear"
const FertilityBellySize = "FertilityBellySize"

# Breeder perks
const BreedStud = "BreedStud"
const BreedStudV2 = "BreedStudV2"
const BreedCumProduction = "BreedCumProduction"
const BreedCumProductionV2 = "BreedCumProductionV2"
const BreedCumProductionV3 = "BreedCumProductionV3"
const BreedCumVolume = "BreedCumVolume"
const BreedCumVolumeV2 = "BreedCumVolumeV2"
const BreedCumVolumeV3 = "BreedCumVolumeV3"
const BreedBreedersBliss = "BreedBreedersBliss"
const BreedRapidConception = "BreedRapidConception"
const BreedCumInflationHeat = "BreedCumInflationHeat"
const BreedExtraTooltipInfo = "BreedExtraTooltipInfo"
const BreedStreak = "BreedStreak"
const BreedCockSlap = "BreedCockSlap"
