extends Node
class_name StatusEffect

const Bleeding = "Bleeding"
const Collapsed = "Collapsed"
const ArmsBound = "ArmsBound"
const HandsBlocked = "HandsBlocked"
const LegsBound = "LegsBound"
const Blindfolded = "Blindfolded"
const Gagged = "Gagged"
const Muzzled = "Muzzled"
const Naked = "Naked"
const Exhausted = "Exhausted"
const CoveredInCum = "CoveredInCum"
const NPCCoveredInCum = "NPCCoveredInCum"
const HasCumInsideVagina = "HasCumInsideVagina"
const HasCumInsideMouth = "HasCumInsideMouth"
const HasCumInsideAnus = "HasCumInsideAnus"
const Intoxicated = "Intoxicated"
const TimedEffects = "TimedEffects"
const TimedEffectsTurns = "TimedEffectsTurns"
const LubedUp = "LubedUp"
